var menuNumber = null;
var musicVolume = 0;
var musicVolumeMJ=0;
var musicMuted = false;
var soundFX;
var soundMJ;

var i=0;

var vel = 350;
var velc = 200;
var vell = 300;
var vely = 400;
var stat = 0; // game offs
var modo;
var semestre = 1;
var player;
var musicVolume;
var soundFX;
var player2;
var cerveja;
var livro;
var locais = new Array("BAR","TORRE C","TORRE G","SALA 1","SALA 2","SALA 3","SALAS","JARDIM","SECRETARIA");
var posicao=locais[1];
var pass, cUC, chave;
var cUC_state = 0, pass_state = 0, quiz_state=0, aula_state=0, limpar_state=0;
var papelcartao;
var listarefas1 = new Array("Cartão UC [Secretaria]\n","Palavra-Passe [HelpDesk]\n","QUIZ [Núcleo]\n","Limpa o DEI\n","Aula de AMI [Sala C.1]\n");
var listarefas2 = new Array("Estudar para o Exame [Sala C.1]\n","Lanche no DEI\n","Praxe [Jardim]\n","Queima das Fitas [Sala G.1]\n");
var listarefas3 = new Array("Projeto de Multimédia [Sala G.2]\n","Cenas\n","Ajudar o Caloiro\n","Introdução à Programação [Sala G.2]\n");
var perguntas = new Array("Qual o bar favorito\ndo estudante de informática?\n","Em que dia de Maio \nse vai realizar o convívio?\n","Quantas torres tem o DEI?\n");
var respostas1 = new Array("Moelas","Bigorna","NB","QuenteBar");
var respostas2 = new Array("24","26","28","14");
var respostas3 = new Array("6","4","5","7");
var nTarefas= listarefas1.length;
var resp;
var final;
var bot1, bot2, bot3, bot4;
var a, e, p;
var sala, torre=locais[1];
var center = new Array(625,450);
var pos = new Array(625,700);
var cursors, spacebar, enter,sair;
var fundo;
var untz;
var i = 0;
var score = 0;
var beerpapel;
var tentativas = 0;
var fireTime = 0;
var bonusTime = 0;
var enemyTime = 0;
var timeNow = 0;
var secretariaLimpo=0,corredorLimpo=0,salasLimpo=0,barLimpo=0;
var trash_obj;
var style, style2;
var life;
var info;
var pontuacao;
